/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.rental.utils;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 *  Vypocita SHA-512 pro zadany vstupni retezec
 * @author https://www.geeksforgeeks.org/sha-512-hash-in-java/
 */
public class SHA512  {
    // Java program to calculate SHA-512 hash value 

    public static String getSHA512(String input) {
        if (input==null) {
            return null;
        }
        try {
            // getInstance() method is called with algorithm SHA-512 
            MessageDigest md = MessageDigest.getInstance("SHA-512");

            // digest() method is called 
            // to calculate message digest of the input string 
            // returned as array of byte 
            StringBuilder sb = new StringBuilder();
            for (byte b : md.digest(input.getBytes())) {                
                sb.append(String.format("%02X", b));
            }
            String hashtext = sb.toString();
            // return the HashText 
            return hashtext;
        } // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    // Driver code 
    public static void main(String args[]) throws NoSuchAlgorithmException {

        System.out.println("HashCode Generated by SHA-512 for: ");

        String s1 = "GeeksForGeeks";
        System.out.println("\n" + s1 + " : \n" + getSHA512(s1));
        String s2 = "hello world";
        System.out.println("\n" + s2 + " : \n" + getSHA512(s2));
        String s3 = "daniela";
        System.out.println("\n" + s3 + " : \n" + getSHA512(s3));
        String s4 = "Daniela";
        System.out.println("\n" + s4 + " : \n" + getSHA512(s4));

    }
}
